name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions: write-all
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Make b
      run: make b
      
    - name: Run 
      run: make run

    - name: check
      run: make check
